#!/bin/sh
# make install things for testing
set -e

echo "Installing S3/Auth server files..."
./installhelper.sh /
systemctl daemon-reload

echo "S3 server and Auth server are setup."
echo "Setup nginx using configuration similar to nginx.conf.sample."
echo "Check the README.md for how to start/stop services."
