S3_MOTR_MAX_UNITS_PER_REQUEST
S3_MOTR_MAX_IDX_FETCH_COUNT
S3_MOTR_MAX_RPC_MSG_SIZE
S3_MOTR_CASS_MAX_COL_FAMILY_NUM
S3_MOTR_READ_POOL_MAX_THRESHOLD
S3_LIBEVENT_MAX_READ_SIZE
S3_LIBEVENT_POOL_MAX_THRESHOLD
