@startuml

header Delete Multiple Objects\n By Ivan Tishchenko\n 2020-11-25

title Delete Multiple Objects

skinparam activity {
  BackgroundColor<< Client >> Cyan
  BackgroundColor<< Auth >> Orange
}

(*) --> "Client: Send Request to delete <Nobj> objects\n<Nobj> = 1..1000" << Client >>
--> "S3->Motr: Load Bucket Metadata\n(2 Motr KVS reads)"
--> "S3->Auth: Authentication and authorization\n(Does user have access to the bucket?)" << Auth >>
--> S3->Motr: Fetch <N> s3 obj metadata entries from Motr KVS\n(N is currently 25)
if "All objects loaded?" then
 -->[no] iterate
 -> S3->Motr: Fetch <N> s3 obj metadata entries from Motr KVS\n(N is currently 25)
else
 -->[yes] S3->Motr: Create <Nobj> "probable delete" entries in Motr KVS index\n(To help revert/recover/redo/finalize in case of failure)\nThis is one single Clovis call.
 --> S3->Motr: Delete s3 metadata of objects from Motr KVS.\nSingle Clovis call to delete <Nobj> entries from KVS index.
 --> S3: Send "Success" response to client << Client >>
 --> [continue processing in background] S3->Motr: Delete all <Nobj> Motr objects\nOne single Clovis call.
 --> S3->Motr: Delete all <Nobj> "probable delete" entries.\nSingle Clovis call.\n(Entries no longer needed as objects are already fully deleted.)
 --> (*)
endif

@enduml
