apiVersion: v1
kind: Secret
metadata:
 name: cortx-secret
type: Opaque
stringData:
  openldap-secret: seagate2
  kafka-secret: kafka-password
  consul-secret: consul-password
  common-secret: common-password
  s3-auth-secret: ldapadmin
  csm-auth-secret: csm-auth-password
  csm-mgmt-secret: csm-mgmt-password
