apiVersion: v1
kind: Pod
metadata:
  name: symas-ldap-pod
spec:
  containers:
    - name: ldap
      image: ghcr.io/seagate/symas-openldap:2.4.58
      imagePullPolicy: Never
      ports:
        - containerPort: 389
          name: "ldapport"
      command:
         - "/opt/entrypoint.sh"
      args:
         - "rootdnpassword"
         - "seagate2"
