kind: PersistentVolume
apiVersion: v1
metadata:
  name: cortx-config-pv
spec:
  storageClassName: config-pv
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/pv"
