apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-cortx
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  volumeName: etc-cortx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-log-cortx
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  volumeName: var-log-cortx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-data-cortx
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  volumeName: var-data-cortx
