apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-motr
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  volumeName: var-motr
