apiVersion: v1
kind: PersistentVolume
metadata:
  name: var-motr
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: var-motr
  local:
    path: /var/motr
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-name
          operator: In
          values:
          - node1
